name: Email For Fasttrack
on:
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }} 
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'KIAS2000 Migration Mail'
          body: 'Hello , How Are you!'
          to: ${{secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_USERNAME }}
