name: Send Email DEMO

on:
  workflow_dispatch:
    inputs:
      email_date:
        description: 'Date of the email (format: YYYY-MM-DD)'
        required: true
        default: '01.01.2024'
      email_SRT:
        description: 'Enter the SRT Number'
        required: true
        default: "Z_SRT123"
      email_application:
        description: 'Enter the application'
        required: true
        type: choice
        options:
          - Unix
          - Citrix
          - Unix and Citrix
jobs:
  send_email:
    runs-on: ubuntu-linux
    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'KIAS2000 Migration on ${{ github.event.inputs.email_date }} | ${{ github.event.inputs.email_SRT }} | Fasttrack'
          body: | 
               Hello Team, 
               Tommorow, We have ${{ github.event.inputs.email_application}} FastTrack planned at 6 CET.
              
               The Binaries listed in attached html file is going to deploy in this FastTrack.
               
               Please confirm, if you have any activity during that time span.

               Kindly share SPOC's details for Sanity purpose.

               Regards,
               Tejas
          to: crownardio@gmail.com, kawsahiba@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
