name: Send Email DEMO 

on:
  workflow_dispatch:
    inputs:
      email_date:
        description: 'Date of the email'
        required: true
        default: '01.01.2024'
      email_SRT:
        description: 'Enter the SRT Number'
        required: true
        default: "Z_SRT123"
      email_application:
        description: 'Enter the application'
        required: true
        type: choice
        options:
          - Unix
          - Citrix
          - Unix and Citrix
jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'KIAS2000 Migration on ${{ github.event.inputs.email_date }} | ${{ github.event.inputs.email_SRT }} | Fasttrack'
          body:|
               <html>
               <head>
                 <style>
                   .application-name {
                     font-family: Arial, sans-serif;
                     font-size: 16px;
                   }
                 </style>
               </head>
               <body>
               Hello Team,<br><br>
               Tomorrow, we have <span class="application-name">${{ github.event.inputs.email_application }}</span> FastTrack planned at 6 CET.<br><br>
               The binaries listed in the attached HTML file are going to be deployed in this FastTrack.<br><br>
               Please confirm if you have any activity during that time span.<br><br>
               Kindly share SPOC's details for sanity purposes.<br><br>
               Regards,<br>
               Tejas
               </body>
               </html>
          to: crownardio@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          content_type: 'text/html'|
               <html>
               <head>
                 <style>
                   .application-name {
                     font-family: Arial, sans-serif;
                     font-size: 16px;
                   }
                 </style>
               </head>
               <body>
               Hello Team,<br><br>
               Tomorrow, we have <span class="application-name">${{ github.event.inputs.email_application }}</span> FastTrack planned at 6 CET.<br><br>
               The binaries listed in the attached HTML file are going to be deployed in this FastTrack.<br><br>
               Please confirm if you have any activity during that time span.<br><br>
               Kindly share SPOC's details for sanity purposes.<br><br>
               Regards,<br>
               Tejas
               </body>
               </html>
          to: crownardio@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          content_type: 'text/html'
