name: Send Email Manually

on:
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Manual Email Trigged'
          body: 'This email was sent manually via GitHub Actions.'
          to: recipient@example.com
          from: ${{ secrets.EMAIL_USERNAME }}
